# Generated by Django 4.1.7 on 2023-04-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='playlists',
            field=models.ManyToManyField(to='movie.playlist'),
        ),
    ]
