# Generated by Django 4.2.3 on 2023-12-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
